version: '3.8'

services:
  # PostgreSQL база данных
  postgres:
    image: postgres:15
    container_name: avtogost77_crm_postgres
    environment:
      POSTGRES_DB: avtogost77_crm
      POSTGRES_USER: avtogost77
      POSTGRES_PASSWORD: avtogost77_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - avtogost77_crm_network

  # FastAPI Backend
  backend:
    build: ./backend
    container_name: avtogost77_crm_backend
    environment:
      DATABASE_URL: postgresql://avtogost77:avtogost77_password@postgres:5432/avtogost77_crm
      SECRET_KEY: avtogost77_secret_key_2025
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - avtogost77_crm_network
    volumes:
      - ./backend:/app

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: avtogost77_crm_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - avtogost77_crm_network

volumes:
  postgres_data:

networks:
  avtogost77_crm_network:
    driver: bridge
