version: '3.8'

services:
  # PostgreSQL база данных
  postgres:
    image: postgres:15-alpine
    container_name: avtogost77_crm_postgres
    environment:
      POSTGRES_DB: avtogost77_crm
      POSTGRES_USER: avtogost77
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-avtogost77_secure_2025}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Backend API (Python FastAPI)
  backend:
    image: python:3.11-slim
    container_name: avtogost77_crm_backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://avtogost77:${POSTGRES_PASSWORD:-avtogost77_secure_2025}@postgres:5432/avtogost77_crm
      - SECRET_KEY=${SECRET_KEY:-avtogost77_crm_secret_key}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID:-@avtogost77}
    depends_on:
      - postgres
    restart: unless-stopped
    command: >
      bash -c "pip install uvicorn fastapi pydantic python-dotenv loguru httpx jinja2 weasyprint num2words python-multipart &&
               python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data:
