#!/bin/bash

echo "🗺️ Генерирую новый sitemap.xml..."

# Создаем новый sitemap.xml
cat > sitemap.xml << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>https://avtogost77.ru/</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>daily</changefreq>
        <priority>1.0</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/services.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/contact.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>monthly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/about.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>monthly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/help.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>monthly</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/faq.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>monthly</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/privacy.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>yearly</changefreq>
        <priority>0.5</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/terms.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>yearly</changefreq>
        <priority>0.5</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/track.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>monthly</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/urgent-delivery.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/self-employed-delivery.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/ip-small-business-delivery.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/transportnaya-kompaniya.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/sbornye-gruzy.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/dostavka-na-marketpleysy.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/rc-dostavka.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/gruzoperevozki-spb.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/gruzoperevozki-moskva-nizhny-novgorod.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/gruzoperevozki-moskva-ekaterinburg.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/gruzoperevozki-moskva-novosibirsk.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/gruzoperevozki-moskva-kazan.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/gruzoperevozki-moskva-rostov.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/gruzoperevozki-moskva-chelyabinsk.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/gruzoperevozki-moskva-samara.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/gruzoperevozki-moskva-ufa.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/gruzoperevozki-moskva-perm.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/gruzoperevozki-moskva-voronezh.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/gruzoperevozki-moskva-kursk.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/gruzoperevozki-moskva-lipetsk.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/gruzoperevozki-moskva-tambov.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/gruzoperevozki-moskva-orel.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/gruzoperevozki-moskva-tula.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/gruzoperevozki-moskva-belgorod.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/gazel-gruzoperevozki.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/trehtonnik-gruzoperevozki.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/pyatitonnik-gruzoperevozki.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/desyatitonnik-gruzoperevozki.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/fura-20-tonn-gruzoperevozki.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/poputnyj-gruz.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/dogruz.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/pereezd-moskva.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/perevozka-mebeli.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/perevozka-medoborudovaniya.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/dostavka-gruzov.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/gruzovoe-taksi.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/sluzhba-dostavki.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/logisticheskaya-kompaniya.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/gruzoperevozki-iz-moskvy.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/gruzoperevozki-po-moskve.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/logistika-dlya-biznesa.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/legal-minimum.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>monthly</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://avtogost77.ru/news.html</loc>
        <lastmod>2025-08-27</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
</urlset>
EOF

echo "✅ Новый sitemap.xml создан!"
echo "📊 Статистика:"
echo "   - Всего страниц: $(grep -c '<url>' sitemap.xml)"
echo "   - Дата обновления: 2025-08-27"
